### ISSUE TITLE
Создание скрипта для инициализации БД

### ISSUE THREAD

**Issue by slaeme** [urfu-2016/team1#23]
БД инициализируется тестовыми данными.

**Comment by slaeme** [comment]
Предлагаю такую архитектуру БД.
Задавайте свои вопросы.
Особенно приветствуются вопросы типа: "А как мы узнаем кто поставил лайк?" или "Такой запрос будет очень долгим ...". Ну и если что не понятно, то спрашивайте.

![bd](https://cloud.githubusercontent.com/assets/22623111/24283116/b814357a-1085-11e7-8741-fb13b42911e5.PNG)

**Comment by fakefeik** [comment]
Выглядит норм
